# Generated by Django 2.1.2 on 2018-10-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foreignkey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('instrucutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreignkey.FCUser')),
            ],
        ),
    ]
