# Generated by Django 2.1.2 on 2018-10-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_auto_20181008_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='starts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], help_text='sml 중 선택', max_length=1),
        ),
    ]
