# Generated by Django 2.1.2 on 2018-10-12 02:59

from django.db import migrations, models
import django.db.models.deletion
import inheritance.multi_table.models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant1',
            fields=[
                ('place1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multi_table.Place1')),
                ('serves_hot_dogs', models.BooleanField(default=False)),
                ('serves_pizza', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Inheritance_Multitable_Restaurant',
            },
            bases=('multi_table.place1',),
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place_ptr',
        ),
        migrations.RenameModel(
            old_name='Place',
            new_name='Place1',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='restaurant1',
            name='old_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(inheritance.multi_table.models.get_removed_place), related_name='old_restaurants', related_query_name='old_restaurant', to='multi_table.Place1', verbose_name='이전 가게 주소'),
        ),
    ]
