# Generated by Django 2.1.2 on 2018-10-12 03:22

from django.db import migrations, models
import django.db.models.deletion
import inheritance.multi_table.models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='old_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(inheritance.multi_table.models.get_removed_place), related_name='old_restaurants', related_query_name='old_restaurant', to='multi_table.Place', verbose_name='이전 가게 주소'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multi_table.Place'),
        ),
    ]
