# Generated by Django 2.1.2 on 2018-10-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0004_auto_20181010_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_set', related_query_name='group', through='many_to_many.Membership', to='many_to_many.Person'),
        ),
    ]
