# Generated by Django 2.1.2 on 2018-10-11 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_base_classes', '0003_auto_20181011_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_base_classes_photopost_set', related_query_name='abstract_base_classes_photopost', to='abstract_base_classes.RelatedUser'),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_base_classes_textpost_set', related_query_name='abstract_base_classes_textpost', to='abstract_base_classes.RelatedUser'),
        ),
    ]
