# Generated by Django 2.1.2 on 2018-10-12 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NormalUser',
            new_name='User1',
        ),
    ]
