# Generated by Django 2.1.2 on 2018-10-12 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20181012_0352'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user1',
            table='Inheritance_Proxy_User1',
        ),
    ]
